export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const REGISTER_USER = "REGISTER_USER"
export const UPDATE_USER_INFO = "UPDATE_USER_INFO"
export const GET_USER_BY_ID = "GET_USER_BY_ID"

export const AUTH_USER = "AUTH_USER"
export const GET_EMAIL_NUMBER = "GET_EMAIL_NUMBER"

export const GET_ALL_BOARD = "GET_ALL_BOARD"
export const GET_DETAIL_BOARD = "GET_DETAIL_BOARD"
export const DELETE_BOARD = "DELETE_BOARD"
export const CREATE_BOARD = "CREATE_BOARD"
export const UPDATE_BOARD = "UPDATE_BOARD"
export const SEARCH_BOARD = "SEARCH_BOARD"

export const ADD_SCRAP = "ADD_SCRAP"
export const GET_SCRAP = "GET_SCRAP"
export const DELETE_SCRAP = "DELETE_SCRAP"

export const WAITING_REGISTER_USER = "WAITING_REGISTER_USER"
export const ADMISSION_USER = "ADMISSION_USER"
export const REFUSE_USER = "REFUSE_USER"
export const GET_ALL_USERS = "GET_ALL_USERS"

export const GET_RESENT_BOARD = "GET_RESENT_BOARD"
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE"

export const SAVE_COMMENT = "SAVE_COMMENT"
export const GET_COMMENTS = "GET_COMMENTS"
export const UPDATE_COMMENT = "UPDATE_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"
